version: "3.8"

services:

  my-sba:
    image: bellsoft/liberica-openjdk-alpine:17
    container_name: mysbaimage_login
    ports:
      - 8088:8080
      - 8008:8000
    environment:
      SPRING_RABBITMQ_HOST: 3.94.244.118
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    expose:
      - "8000"
    depends_on:
      - my-db
    networks:
      - my-net
      - rabbit-net
    volumes:
      - ./build/libs/REC_Login-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  my-db:
    image: mongo:5.0
    container_name: mongodbimage_login
    ports:
      - 27025:27017
    networks:
      - my-net
networks:
  my-net:
    driver:
      "bridge"
  rabbit-net:
    external: true


