version: "3.8"

services:
  my-rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-net
networks:
  rabbit-net:
    external: true

